// Stub regenerated by `npx convex dev` / `npx convex codegen`.
// The frontend imports `api.bookings.submit` etc. via Convex's anyApi proxy;
// Vite tree-shakes this stub out once the real generated file is present.
import { anyApi } from "convex/server";
export const api = anyApi;
export const internal = anyApi;
