// Stub regenerated by `npx convex dev` / `npx convex codegen`.
// Kept here so the Vite build works before Convex has been initialized.
// Once you run convex codegen, this file is overwritten with real types.
export declare const api: any;
export declare const internal: any;
